### ISSUE TITLE
Spamming one release

### ISSUE THREAD

**Issue by UltraFeed** [chofnar/release-bot#115]
bot spamming one release, "see all repos" button not responding
![image](https://github.com/chofnar/release-bot/assets/49344045/c771e4aa-1e5e-4744-9e45-2e1db3266a19)

**Comment by chofnar** [comment]
Sorry, I was away for the holidays and did not notice your issue. Does this still happen? At a first inspection I don't see anything wrong with the repo or the database

**Comment by UltraFeed** [comment]
I blocked bot, because it was spamming, now restarted it and "see all repos" still unresponsive.

Upd: still spamming one release
![Screenshot_20240106-161546_Plus](https://github.com/chofnar/release-bot/assets/49344045/8b4a35d5-b5c8-4a6d-9fb6-842969ac054b)

Upd2: bot sent another release, once, as expected

**Comment by chofnar** [comment]
I did some updates to the logic alongside some cleanup. If you're still willing to test it, please have another go. You will have to add the repo again though.

**Comment by UltraFeed** [comment]
Added repo again. Buttons are working, but this repo doesn't have "delete" or "enable pre releases" buttons

[
![Screenshot_20240123-002555_AyuGram](https://github.com/chofnar/release-bot/assets/49344045/ee47a97b-0964-45a0-a8ba-5cd0b16446e4)
](url)

**Comment by chofnar** [comment]
Can you give me a link to that repo, please?

**Comment by UltraFeed** [comment]
https://github.com/WSTxda/MicroG-RE

**Comment by chofnar** [comment]
I think this happens because of the amount of buttons in the message. I will need to implement some sort of pagination. For the moment, the buttons should show if you delete one or two of your other repos. I will implement this functionality in the coming days. Anyway, even if you don't see the buttons right now, you will still be notified, as the repo is registered in the database.

**Comment by UltraFeed** [comment]
Deleted one repo and buttons appeared. So the limit now is 25 repos.

**Comment by chofnar** [comment]
Hey, I implemented pagination for the repo list. The limit should be gone now. I also improved the navigation a bit. You will also hopefully find that the bot is a lot more responsive now, as it's running continuously now. Please let me know how this works for you :)

**Comment by UltraFeed** [comment]
I have 25 repos added. First and second page of list are working well, and I can switch between them, but when I try to switch to the third page, button "next" not responding. Maybe this bug happening because you are expecting list of 10 elements, but the last page could contain list from 1 to 10 elements?

Upd1: bot responding time has increased twice or more, according to my feelings.
Upd2: added 5 more repos, so my total repos is 30. Still can't switch to the last page. Needs investigation.

Upd3: Also, I think that you should think about sorting of repos, for example:
First step: sorting all repos by autor
Second step: sorting all repos by their names (respecting sorting by autor)

Example unsorted:

Alex/website
Alex/app
John/application
John/tests
Alex/parser
John/bot

Example sorted:

Alex/app
Alex/parser
Alex/website
John/application
John/bot
John/tests

Upd4: make "pre", "delete", "latest release" buttons smaller and "autor/repo" button bigger if possible

**Comment by chofnar** [comment]
- There was an issue with repos that didn't have releases, preventing the buttons from showing up. I fixed it now, it should work.
- Does it really run slower? I was running the bot in Cloud Run and it took like 30 seconds for it to wake up, but now it's listening all the time. In theory it should certainly be faster.
- I'm planning to implement alphabetic sorting, but I need to switch the database to something with tables, as the one I'm using now is not really the best fit for the project, even if it technically works.
- Buttons appearance: Unfortunately that is out of my power as it's Telegram who chooses how the buttons look and their layout on rows/columns. I'll think of a new layout that will hopefully improve the navigation experience.

**Comment by UltraFeed** [comment]
Bot is running faster, you misunderstood me. Everything works as expected, so I'm closing the issue.
