### ISSUE TITLE
Error adding repo

### ISSUE THREAD

**Issue by UltraFeed** [chofnar/release-bot#121]
Trying to add https://github.com/bmax121/APatch
![Screenshot_20240124-165551_AyuGram](https://github.com/chofnar/release-bot/assets/49344045/bab3cde3-bde5-4699-ab25-6af47cf50b3d)

Same error with https://github.com/janhq/jan

**Comment by chofnar** [comment]
Whoops, I messed up some credentials. Should be fine now.

**Comment by UltraFeed** [comment]
Fixed now
